### ISSUE TITLE
powershell scripts are not connecting mssql server

### ISSUE THREAD

**Issue by arun123ks** [sfuerte/zbx-mssql#3]
Hi, 

Thanks for this nice tool.
I am trying to configure it but scripts are giving error and not connecting the mssql server. 

I am getting below error, please help me to fix it.

PS C:\Users\Administrator> C:\Zabbix\scripts\mssql_basename.ps1
Exception calling "Open" with "0" argument(s): "A network-related or instance-specific error occurred while 
establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance 
name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, 
error: 40 - Could not open a connection to SQL Server)"
At C:\Zabbix\scripts\mssql_basename.ps1:30 char:1
+ $connection.Open()
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SqlException
 
Exception calling "Fill" with "1" argument(s): "A network-related or instance-specific error occurred while 
establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance 
name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, 
error: 40 - Could not open a connection to SQL Server)"
At C:\Zabbix\scripts\mssql_basename.ps1:39 char:1
+ $SqlAdapter.Fill($DataSet) > $null
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : SqlException
 
{
 "data":[

**Comment by sfuerte** [comment]
check lines ##14-25 of the scripts, mssql_basename.ps1:

```
#define the variables for connecting to MS SQL. $uid и $pwd need to authenticate windows
$SQLServer = $(hostname.exe)
#$uid = "Login" 
#$pwd = "Password"

#Create a connection to MSSQL

#If windows authentication
#$connectionString = "Server = $SQLServer; User ID = $uid; Password = $pwd;"

#If integrated authentication
$connectionString = "Server = $SQLServer; Integrated Security = True;"
```

By default, it connects to the same host and assumes it doesn't require login/pass. 
You need to update the script it to get it working if your server requires username&pass. 

Will change the powershell script later to pass them as arguments.
