### ISSUE TITLE
Compatibility with Zabbix 3.2

### ISSUE THREAD

**Issue by Rapsoulis** [sfuerte/zbx-mssql#4]
Hello, would it be possible to make this template backwards compatible with Zabbix version 3.2?

Thanks for your time.

**Comment by sfuerte** [comment]
Hello, 

Sorry for the delay. 

What part of the template isn't compatible with 3.2? We have them since at least 3.0 and didn't have any issues.

**Comment by Digitalpit** [comment]
When I'm trying to import zbx_template_mssql.xml file into Zabbix 3.2.7, result is:
_Import failed
Details
Invalid tag "/zabbix_export/templates/template(1)/items/item(1)": unexpected tag "preprocessing"._
