### ISSUE TITLE
Cannot obtain performance information from collector

### ISSUE THREAD

**Issue by bkhaira** [sfuerte/zbx-mssql#5]
Hi sfuete,

I am hoping you can help me :-) 

I have successfully loaded zbx-mssql template into my Zabbix 3.4 server and it is fetching data with exception of SQL Server Statistic counters. 

If I manually add $DBInstance in the perf_counter key  I can fetch the data

> perf_counter["\MSSQL$ACT7:Access Methods\Forwarded Records/sec"],

By default perf counter string is perf_counter["\SQLServer:Access Methods\Forwarded Records/sec"]

Where do I need to update the DBname in the perf counter key. Somewhere in ps scripts or is this information collected and added during discovery rule phase?

Thanks in advance....

**Comment by bkhaira** [comment]
I have resolved the issue by using Micros in the template.

**Comment by cgratelli** [comment]
Please bkhaira, could you give more fix details? Line number, code replaced... 

Thanks in advance

**Comment by bkhaira** [comment]
Sorry, no changes to the template as such. Under Host, I created a Macros to provide $SQLinstance name i.e. ({$SQLINSTANCE} = ACT7). 

The mssql.db.discovery via PowerShell is not working for me. For now, I am monitoring one instance per server, instead of databases within those instances. 

Just wondering, if you have spare time and interested for doing paid consultancy work for me? I can use your help with some of the work I am looking to do in Zabbix? If you could you please shoot me your email at bobby@itleap.com.au
