### ISSUE TITLE
perf_counter does not work on windows with a language other than English

### ISSUE THREAD

**Issue by atilaloise** [sfuerte/zbx-mssql#6]
It's not a problem of yours but it's sure to affect users.

For information only: if your windows are not in English, you must translate the perf_counters parameters into your language, according to what is available on the Windows Server performance monitor.

In Sql server 2014 I did not find the key ": Access Methods \"

**Comment by youssefcssiste** [comment]
how you can change ?

**Comment by atilaloise** [comment]
It is a matter of revolve the template and let every item exactly as shown on the windows performance monitor.

Please close this issue.
