### ISSUE TITLE
Template fails to import under Zabbix 3.4.9 (havent tested on others)

### ISSUE THREAD

**Issue by vvolas** [sfuerte/zbx-mssql#9]
Hello,
Template fails to import under Zabbix 3.4.9 (havent tested on others)

`    Error in query [INSERT INTO items (name,type,snmp_community,snmp_oid,delay,history,trends,status,value_type,units,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,description,inventory_link,logtimefmt,jmx_endpoint,key_,trapper_hosts,hostid,master_itemid,flags,itemid) VALUES ('SQL Server, Errors: Errors/sec (Total)','0','','','60s','90d','365d','0','0','','','','0','0','','0','','','','0','','','','','','Number of errors/sec.\r\n\r\nКоличество ошибок/с','0','','','perf_counter[\"\\SQLServer:SQL Errors(_Total)\\Errors/sec\"]','','10166',NULL,'0','34785')] [Incorrect string value: '\xD0\x9A\xD0\xBE\xD0\xBB...' for column 'description' at row 1]
    SQL statement execution has failed "INSERT INTO items (name,type,snmp_community,snmp_oid,delay,history,trends,status,value_type,units,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,description,inventory_link,logtimefmt,jmx_endpoint,key_,trapper_hosts,hostid,master_itemid,flags,itemid) VALUES ('SQL Server, Errors: Errors/sec (Total)','0','','','60s','90d','365d','0','0','','','','0','0','','0','','','','0','','','','','','Number of errors/sec.\r\n\r\nКоличество ошибок/с','0','','','perf_counter[\"\\SQLServer:SQL Errors(_Total)\\Errors/sec\"]','','10166',NULL,'0','34785')".`

**Comment by karthikeyan1215** [comment]
Hi,

im also getting the below error while importing the mssql template on zabbix GUI,
```
Import failed
Details
Error in query [INSERT INTO items (name,type,snmp_community,snmp_oid,delay,history,trends,status,value_type,units,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,description,inventory_link,logtimefmt,jmx_endpoint,key_,trapper_hosts,hostid,master_itemid,flags,itemid) VALUES ('SQL Server, Errors: Errors/sec (Total)','0','','','60s','90d','365d','0','0','','','','0','0','','0','','','','0','','','','','','Number of errors/sec.\r\n\r\nКоличество ошибок/с','0','','','perf_counter[\"\\SQLServer:SQL Errors(_Total)\\Errors/sec\"]','','10265',NULL,'0','29692')] [Incorrect string value: '\xD0\x9A\xD0\xBE\xD0\xBB...' for column 'description' at row 1]
SQL statement execution has failed "INSERT INTO items (name,type,snmp_community,snmp_oid,delay,history,trends,status,value_type,units,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,description,inventory_link,logtimefmt,jmx_endpoint,key_,trapper_hosts,hostid,master_itemid,flags,itemid) VALUES ('SQL Server, Errors: Errors/sec (Total)','0','','','60s','90d','365d','0','0','','','','0','0','','0','','','','0','','','','','','Number of errors/sec.\r\n\r\nКоличество ошибок/с','0','','','perf_counter[\"\\SQLServer:SQL Errors(_Total)\\Errors/sec\"]','','10265',NULL,'0','29692')".
```
Can any one check this and help us to resolve this issue please.
